_wandb:
    value:
        cli_version: 0.21.0
        e:
            z3vf89d174dx8gx8jazud5jbo37zoj5y:
                cpu_count: 4
                cpu_count_logical: 8
                cudaVersion: "11.0"
                disk:
                    /:
                        total: "235518554112"
                        used: "235310309376"
                email: violetsunshades@snu.ac.kr
                executable: C:\Users\viole\AppData\Local\Programs\Python\Python311\python.exe
                git:
                    commit: cf493517620512ce03a88bd065bc97f4722edc04
                    remote: https://github.com/Poodlee/Ecg_Arrhythmia_Detect.git
                gpu: GeForce MX450
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      name: GeForce MX450
                      uuid: GPU-e8fc49a8-8d3d-970c-c912-801fdd5611a6
                host: BOOK-9EH5OI5JHN
                memory:
                    total: "8251056128"
                os: Windows-10-10.0.22631-SP0
                program: <python with no main file>
                python: CPython 3.11.2
                root: C:\Users\viole\OneDrive\바탕 화면\Veritas Lux Mea\year 3\3-1\lab\arrhythmia_detect\Ecg_Arrhythmia_Detect
                startedAt: "2025-07-03T04:10:29.132325Z"
                writerId: z3vf89d174dx8gx8jazud5jbo37zoj5y
        m: []
        python_version: 3.11.2
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 1
                - 16
                - 17
                - 24
                - 61
            "4": 3.11.2
            "5": 0.21.0
            "8":
                - 3
            "12": 0.21.0
            "13": windows-amd64
batch_size:
    value: 64
dataset:
    value: MNIST
epochs:
    value: 10
learning_rate:
    value: 0.01
model:
    value: CNN
optimizer:
    value: sgd
weight_decay:
    value: 0
